### ISSUE TITLE
Dont use the same value for the id property in the html

### ISSUE THREAD

**Issue by DevWurm** [DevWurm/rsa_database#15]
Dont use the same value for the id property in the html, use class instead

**Comment by vgerber** [comment]
Herr Berger ist das egal...

**Comment by DevWurm** [comment]
It's incorrect

**Comment by vgerber** [comment]
But it works

**Comment by DevWurm** [comment]
But its not correct, please fix it

**Comment by vgerber** [comment]
i dont know how pls introduce me

**Comment by vgerber** [comment]
fixed
