### ISSUE TITLE
Problem with file up/download (dir)

### ISSUE THREAD

**Issue by vgerber** [DevWurm/rsa_database#20]
move_uploaded_file(./temp/key_priv_up.drsa): failed to open stream: No such file or directory in C:\xampp\htdocs\application\includes\get_post.php on line 83

**Comment by vgerber** [comment]
-> i delete the '/temp' part , do we need a temp folder in htdocs?

**Comment by DevWurm** [comment]
Yes we need, don't manipulate the file paths!
Just create a temp files in htdocd
