### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by vgerber** [DevWurm/rsa_database#3]
Tolator wo bleibt das ERD?

**Comment by Tolator** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/12112511/7452690/367d66ce-f261-11e4-99a4-43f1633f3948.jpg)

**Comment by Tolator** [comment]
![database](https://cloud.githubusercontent.com/assets/12112511/7452741/e36e7ff8-f261-11e4-9f46-f8befd2e98c6.JPG)
