### ISSUE TITLE
Input Variables

### ISSUE THREAD

**Issue by vgerber** [DevWurm/rsa_database#4]
Tolator pls post the input variables

**Comment by Tolator** [comment]
$vorname = $_POST["vorname"];
$nachname = $_POST["nachname"];
$geb = $_POST["geb"];
$plz = $_POST["plz"];
$ort = $_POST["ort"];
$str = $_POST["str"];
$hausnummer = $_POST["hausnummer"];
$tel = $_POST["tel"];
$mail = $_POST["mail"];
