### ISSUE TITLE
function convert_int_to_ascii

### ISSUE THREAD

**Issue by Enceladus-2** [DevWurm/rsa_database#5]
I wonder if the created ascii string is really unique for the integer values which the function receives can be larger than 255. These values depends mainly on the public key N and can be every value which is smaller than N.

**Comment by DevWurm** [comment]
convert_int_to_ascii is only called after decrypting the data, so the input array should only contain valid ascii int representations and so there cant be bigger than 255, am I right?

**Comment by Enceladus-2** [comment]
You are absolutely right. The function is completely valid. I bag your pardon.
