### ISSUE TITLE
Database Structure

### ISSUE THREAD

**Issue by KKegel** [DevWurm/rsa_database#7]
Please add the line 'private_key' directly to the main table, not shown on the website.

Add a new file calling 'db_structure.txt' where is a short overview over the rows and values of the dbase.

**Comment by DevWurm** [comment]
the id of the private key is already added to the main table (see k_id).

**Comment by DevWurm** [comment]
Tolator please add a database.md Markdown file, where you describe the relations and the purposes of the database rows

**Comment by DevWurm** [comment]
Description wouldn't be very useful. SQL Dump is self-explaining.
